<?php
function carName($car)
{
    if ($car == 'C_Offroad_01_F') return 'Offroad';
    elseif ($car == 'C_SUV_01_F') return 'SUV';
    elseif ($car == 'C_Offroad_01_repair_F') return 'Offroad (Repair)';
    elseif ($car == 'O_Heli_Light_02_unarmed_F') return 'PO-30 Orca';
    elseif ($car == 'C_Heli_Light_01_civil_F') return 'M-900';
    elseif ($car == 'B_Quadbike_01_F') return 'Quadbike';
    elseif ($car == 'C_Hatchback_01_F') return 'Hatchback';
    elseif ($car == 'C_Hatchback_01_sport_F') return 'Hatchback Sport';
    elseif ($car == 'C_Van_01_transport_F') return 'Truck';
    elseif ($car == 'C_Van_01_box_F') return 'Truck Boxer';
    elseif ($car == 'C_Van_01_fuel_F') return 'Fuel Truck';
    elseif ($car == 'I_Truck_02_transport_F') return 'Zamak Transport';
    elseif ($car == 'O_Truck_03_transport_F') return 'Tempest Transport';
    elseif ($car == 'B_Truck_01_transport_F') return 'HEMTT Transport';
    elseif ($car == 'O_Truck_02_covered_F') return 'Zamak Transport (Covered)';
    elseif ($car == 'O_Truck_03_covered_F') return 'Tempest Transport (Covered)';
    elseif ($car == 'B_Truck_01_covered_F') return 'HEMTT Transport (Covered)';
    elseif ($car == 'B_Truck_01_box_F') return 'HEMTT Box';
    elseif ($car == 'O_Truck_03_ammo_F') return 'Tempest Ammo';
    elseif ($car == 'I_Truck_02_fuel_F') return 'Zamak Fuel';
    elseif ($car == 'O_Truck_03_fuel_F') return 'Tempest Fuel';
    elseif ($car == 'B_Truck_01_fuel_F') return 'HEMTT Fuel';
    elseif ($car == 'O_Truck_03_device_F') return 'Tempest (Device)';
    elseif ($car == 'I_Heli_Transport_02_F') return 'CH-49 Mohawk';
    elseif ($car == 'O_Heli_Transport_04_F') return 'Mi-290 Taru';
    elseif ($car == 'O_Heli_Transport_04_covered_F') return 'Mi-290 Taru (Transport)';
    elseif ($car == 'O_Heli_Transport_04_box_F') return 'Mi-290 Taru (Cargo)';
    elseif ($car == 'O_Heli_Transport_04_fuel_F') return 'Mi-290 Taru (Fuel)';
    elseif ($car == 'C_Rubberboat') return 'Rescue Boat';
    elseif ($car == 'C_Boat_Civil_01_F') return 'Motorboat';
    elseif ($car == 'B_SDV_01_F') return 'SDV (Submarine)';
    elseif ($car == 'B_G_Offroad_01_F') return 'Offroad';
    elseif ($car == 'B_Heli_Light_01_F') return 'MH-9 Hummingbird';
    elseif ($car == 'O_MRAP_02_F') return 'Ifrit';
    elseif ($car == 'B_G_Offroad_01_armed_F') return 'Offroad (Armed)';
    elseif ($car == 'O_Heli_Transport_04_bench_F') return 'Mi-290 Taru (Bench)';
    elseif ($car == 'O_Heli_Attack_02_black_F') return 'Mi-48 Kajman (Black)';
    elseif ($car == 'B_MRAP_01_F') return 'Hunter';
    elseif ($car == 'I_MRAP_03_F') return 'Strider';
    elseif ($car == 'B_MRAP_01_hmg_F') return 'Hunter HMG';
    elseif ($car == 'I_Heli_light_03_unarmed_F') return 'WY-55 Hellcat (Green)';
    elseif ($car == 'I_Heli_light_03_F') return 'WY-55 Hellcat';
    elseif ($car == 'B_Heli_Transport_01_F') return 'UH-80 Ghost Hawk';
    elseif ($car == 'B_Heli_Transport_03_F') return 'CH-67 Huron';
    elseif ($car == 'B_Heli_Transport_03_unarmed_F') return 'CH-67 Huron (Black)';
    elseif ($car == 'B_Boat_Transport_01_F') return 'Assault Boat';
    elseif ($car == 'C_Boat_Civil_01_police_F') return 'Motorboat (Police)';
    elseif ($car == 'B_Boat_Armed_01_minigun_F') return 'Speedboat Minigun';
    elseif ($car == 'O_Truck_02_Fuel_F') return 'Zamak Fuel';
    elseif ($car == 'O_Truck_03_fuel_F') return 'Tempest Fuel';
    elseif ($car == 'B_Truck_01_ammo_F') return 'HEMTT Ammo';
    elseif ($car == 'O_Truck_02_box_F') return 'Zamak Repair';
    elseif ($car == 'O_Heli_Transport_04_medevac_F') return 'Mi-290 Taru (Medical)';
    elseif ($car == 'O_Boat_Armed_01_hmg_F') return 'Speedboat HMG';
    elseif ($car == 'I_MRAP_03_hmg_F') return 'Strider HMG';
    elseif ($car == 'O_MRAP_02_hmg_F') return 'Ifrit HMG';
    elseif ($car == 'O_Truck_03_Ammo_F') return 'Tempest Ammo';
    elseif ($car == 'Box_IND_AmmoVeh_F') return 'Box_IND_AmmoVeh_F';
    elseif ($car == 'B_Slingload_01_Cargo_F') return 'B_Slingload_01_Cargo_F';
    elseif ($car == 'C_supplyCrate_F') return 'C_supplyCrate_F';
    elseif ($car == 'B_Heli_Attack_01_F') return 'AH-99 Blackfoot';
    elseif ($car == 'B_Truck_01_medical_F') return 'Hemmt Medic';
    elseif ($car == 'O_Truck_03_medical_F') return 'Tempest Medic';
    elseif ($car == 'I_APC_Wheeled_03_cannon_F') return 'Marid';
    elseif ($car == 'O_APC_Wheeled_02_rcws_F') return 'Marid Cop';
    elseif ($car == 'I_Truck_02_covered_F') return 'Zamak Abgedeckt';
    elseif ($car == 'B_Truck_01_mover_F') return 'Hemmt Mover';
    elseif ($car == 'O_MRAP_02_gmg_F') return 'Marid';
    elseif ($car == 'I_APC_Wheeled_03_cannon_F') return 'iFRIT GMG';
    elseif ($car == 'C_Kart_01_Vrana_F') return 'Kart Vrana';
    elseif ($car == 'C_Kart_01_F') return 'Kart';
    elseif ($car == 'C_Kart_01_Fuel_F') return 'Kart Fuel';
    elseif ($car == 'C_Kart_01_Blue_F') return 'Kart Blue';
    elseif ($car == 'C_Kart_01_Green_F') return 'Kart Green';
    elseif ($car == 'C_Kart_01_Orange_F') return 'Kart Orange';
    elseif ($car == 'C_Kart_01_White_F') return 'Kart White';
    elseif ($car == 'C_Kart_01_Yellow_F') return 'Kart Yellow';
    elseif ($car == 'C_Kart_01_Black_F') return 'Kart Black';
    elseif ($car == 'C_Kart_01_Red_F') return 'Kart Red';
    elseif ($car == 'O_Truck_02_Ammo_F') return 'Zamak Ammo';
    else return $car;
}